### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sonka93** [nilsnolde/ORStools#11]
Hallo,
I've got my own API. When I am doing accessibility areas there appear an error:

2017-05-19T13:11:00	1	Traceback (most recent call last):
			  File "C:/Users/Sonia/.qgis2/python/plugins\OSMtools\osm_tools_access.py", line 243, in pointAnalysis
			    self.dissolveFields(layer_out, fields_diss)
			  File "C:/Users/Sonia/.qgis2/python/plugins\OSMtools\osm_tools_access.py", line 308, in dissolveFields
			    layer_dissolved = QgsMapLayerRegistry.instance().mapLayersByName("Dissolved")[-1]
			IndexError: list index out of range

What does it mean? Despite this, accessibility areas are on the map.

**Comment by hoge6b01** [comment]
Hello, there was an ongoing discussion about exactly the same error. Look here [https://github.com/nilsnolde/ORStools/issues/8](url)

**Comment by sonka93** [comment]
That's true, sorry  ;)
