### ISSUE TITLE
ValueError: could not convert string to float: Long

### ISSUE THREAD

**Issue by riccardoklinger** [nilsnolde/ORStools#6]
Tried to open the menu, received this error:
configuration: QGIS 2.16.2
windows 7, 64bit
just one layer:
1) Layer called cities (attributes: ID, name) 

Project was in CRS 4326

Traceback (most recent call last):
			  File "C:/Users/rikl/.qgis2/python/plugins\OSMtools\osm_tools.py", line 233, in run
			    self.route_anal.route()
			  File "C:/Users/rikl/.qgis2/python/plugins\OSMtools\osm_tools_routing.py", line 228, in route
			    point_list = [float(x) for x in start_features[0].split(",")]
			ValueError: could not convert string to float: Long

But I was not able te replicate the error.

**Comment by nilsnolde** [comment]
If it´s not reproducible, I guess I can close this issue?!
