### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by riccardoklinger** [nilsnolde/ORStools#7]
When running in batch mode I received some errors in the python log. Yet the routing finished with success. Here is the error/warning:
```
Python Console 
Use iface to access QGIS API interface or Type help(iface) for more info
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file connectionpool.py, line 788
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file connectionpool.py, line 788
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file connectionpool.py, line 788
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file connectionpool.py, line 788
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file connectionpool.py, line 788
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file connectionpool.py, line 788
```

**Comment by nilsnolde** [comment]
Hi Riccardo,

yes, I´m not sure where those errors come from. I think it has to do with the http connections from `requests`, which don´t close properly for some reason. It only shows up in the interpreter though and doesn´t impact the calculations.

Cheers
Nils
